services:
  - type: web
    name: KandyLand
    env: node
    region: oregon # optional (defaults to oregon. Other regions: ohio, frankfurt, singapore)
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: INSECURE_USE_HTTP # TLS is terminated before reaching the app, so only needs to respond to HTTP.
        value: true
